version: '3.7'

services:
  crdb:
    container_name: cockroach-db
    hostname: crdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=rinha-backend-cluster --insecure
    ports:
      - "26257:26257"
      - "8089:8080"
    networks:
      - rinha_backend_network
  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=postgres
    depends_on:
      - crdb
    networks:
      - rinha_backend_network

networks:
  rinha_backend_network:
    name: rinha_backend_network